name: my_pos
description: A simple offline-first POS app for a small cafe
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  bloc: ^8.1.0
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3
  http: ^0.13.6
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  device_info_plus: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.9.0

flutter:
  uses-material-design: true
flutter_icons:
  image_path: assets/icon/launcher_icon.png
  android: true