name: my_pos
description: POS Kopilibrasi Application
publish_to: 'none'
version: 0.3.0+4

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  bloc: ^8.1.0
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3
  http: ^0.13.6
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  device_info_plus: ^12.3.0
  win32: ^5.15.0
  responsive_sizer: ^3.3.1
  pdf: ^3.10.8
  printing: ^5.12.0
  print_bluetooth_thermal: ^1.1.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: assets/icon/launcher_icon.png